package:
  name: conda-project
  version: "1.0"

source:
  path: ..

build:
  number: 0
  format: tar.bz2
  script_env:
    - ARCH=64

requirements:
  build:
    - cmake
    - nlohmann_json
    - {{ compiler('cxx') }}
  host:
    - nlohmann_json
    - libgcc
  run:
    - libgcc >=12
    - libstdcxx >=12
    - libcxx >=12

test:
  commands:
    - conda-project

about:
  summary: "C++ project using custom JSON and Crypto libraries"
  license: MIT
